export const AUTHOR_TEST_ID = 'AUTHOR_TEST_ID';
export const COURSE_AUTHOR_TEST_ID = 'COURSE_AUTHOR_TEST_ID';
export const COURSE_CARD_TEST_ID = 'COURSE_CARD_TEST_ID';
export const COURSE_FORM_TEST_ID = 'COURSE_FORM_TEST_ID';
export const AUTHORS_CONTAINER_TEST_ID = 'AUTHORS_CONTAINER_TEST_ID';
export const COURSE_AUTHORS_CONTAINER_TEST_ID =
	'COURSE_AUTHORS_CONTAINER_TEST_ID';
